# -*- coding: utf-8 -*-
"""IA_Connect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqBVIPf1tDjb1-nV1Po-hGW5tfUXDPck
"""

# Instala Gradio si no lo tienes
!pip install -q gradio

import gradio as gr
import pandas as pd

# Datos base del asistente
data = {
    "Tipo de negocio": [
        "Moda / Belleza", "Educación / Cursos", "Gastronomía / Restaurantes",
        "Tecnología / Software", "Servicios creativos", "Salud / Bienestar",
        "Consultoría / Finanzas", "Emprendimientos locales"
    ],
    "Red recomendada": [
        "Instagram / TikTok", "YouTube / Instagram", "TikTok / Facebook",
        "LinkedIn / YouTube", "Instagram / Behance", "Instagram / YouTube",
        "LinkedIn / YouTube", "Facebook / WhatsApp Business"
    ],
    "¿Por qué?": [
        "Alto valor visual, viralidad", "Contenido educativo y largo formato",
        "Visual, emocional y viral", "B2B técnico, autoridad",
        "Portafolio visual y estilo", "Confianza y demostración",
        "Autoridad y networking", "Atención directa y confianza local"
    ],
    "Formatos ideales": [
        "Reels, historias, lives", "Videos largos, carruseles",
        "Videos cortos, promociones", "Demos, artículos, webinars",
        "Carruseles, reels", "Testimonios, reels",
        "Videos educativos, artículos", "Publicaciones, catálogos"
    ]
}
df = pd.DataFrame(data)

# Función del asistente
def recomendar_red(tipo_negocio):
    resultado = df[df["Tipo de negocio"] == tipo_negocio].iloc[0]
    return (
        f"✅ Red recomendada: {resultado['Red recomendada']}\n\n"
        f"📌 ¿Por qué?: {resultado['¿Por qué?']}\n\n"
        f"🎯 Formatos ideales: {resultado['Formatos ideales']}"
    )

# Interfaz Gradio
gr.Interface(
    fn=recomendar_red,
    inputs=gr.Dropdown(choices=list(df["Tipo de negocio"]), label="Selecciona tu tipo de negocio"),
    outputs="text",
    title="Asistente IA Connect",
    description="Recibe una recomendación de red social ideal según tu tipo de emprendimiento"
).launch()